% Autogenerated with DRAKON Editor 1.21

-module(elli_machine_flow).
-export([handle_request/1]).
%%
%% Header
%%

-include_lib("elli/include/elli.hrl").
-include("elli_machine.hrl").
-include("elli_machine_internal.hrl").




call(Name, State) ->
    % item 369
    elli_machine_controller:call(Name, State)
.

delete_flow(State) ->
    % item 377
    State
.

exchange(State) ->
    % item 351
    State#machine_flow_state.exchange
.

finalize(State) ->
    % item 296
    HasRespBody = has_resp_body(State),
    % item 171
    if HasRespBody -> 
        % item 189
        {MultipleChoices, S1} = call(multiple_choices, State),
        % item 174
        if MultipleChoices -> 
            % item 178
            % Multiple Choices
            respond(300, S1)
        ; true ->
            % item 192
            % OK
            respond(200, S1)
        end
    ; true ->
        % item 177
        % No Content
        respond(204, State)
    end
.

get_flow(State) ->
    % item 194
    Req = request(State),
    {ResourceExists, S1} = call(resource_exists, State),
    % item 6
    if ResourceExists -> 
        % item 301
        {ETag, S2} = call(generate_etag, S1),
        IfMatchHeader = 
            elli_request:get_header(<<"If-Match">>, Req),
        % item 23
        if IfMatchHeader =:= undefined -> 
            % item 290
            {LastModified, S3} = call(last_modified, S2),
            % item 302
            if LastModified =:= undefined -> 
                % item 284
                {Expires, S4} = call(expires, S3),
                S5 = set_etag(ETag, S4),
                S6 = set_expires(Expires, S5),
                % item 304
                IfNoneMatch = 
                    elli_request:get_header(<<"If-None-Match">>, Req),
                % item 36
                if IfNoneMatch =:= undefined -> 
                    % item 39
                    if IfNoneMatch =:= <<"*">> -> 
                        % item 44
                        % Not Modified
                        error(304, S6)
                    ; true ->
                        % item 298
                        ETagMatches = 
                            match_etag(ETag, IfMatchHeader),
                        % item 45
                        if ETagMatches -> 
                            % item 44
                            % Not Modified
                            error(304, S6)
                        ; true ->
                            % item 46
                            S7 = set_last_modified(LastModified, S6),
                            S8 = S7, 
                            
                            % call(provide_content, S7),
                            
                            io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                            % item 187
                            finalize(S8)
                        end
                    end
                ; true ->
                    % item 46
                    S7 = set_last_modified(LastModified, S6),
                    S8 = S7, 
                    
                    % call(provide_content, S7),
                    
                    io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                    % item 187
                    finalize(S8)
                end
            ; true ->
                % item 289
                IfModifiedSince =
                    elli_request:get_header(<<"If-Modified-Since">>, Req),
                % item 33
                if IfModifiedSince =:= undefined -> 
                    % item 284
                    {Expires, S4} = call(expires, S3),
                    S5 = set_etag(ETag, S4),
                    S6 = set_expires(Expires, S5),
                    % item 304
                    IfNoneMatch = 
                        elli_request:get_header(<<"If-None-Match">>, Req),
                    % item 36
                    if IfNoneMatch =:= undefined -> 
                        % item 39
                        if IfNoneMatch =:= <<"*">> -> 
                            % item 44
                            % Not Modified
                            error(304, S6)
                        ; true ->
                            % item 298
                            ETagMatches = 
                                match_etag(ETag, IfMatchHeader),
                            % item 45
                            if ETagMatches -> 
                                % item 44
                                % Not Modified
                                error(304, S6)
                            ; true ->
                                % item 46
                                S7 = set_last_modified(LastModified, S6),
                                S8 = S7, 
                                
                                % call(provide_content, S7),
                                
                                io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                                % item 187
                                finalize(S8)
                            end
                        end
                    ; true ->
                        % item 46
                        S7 = set_last_modified(LastModified, S6),
                        S8 = S7, 
                        
                        % call(provide_content, S7),
                        
                        io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                        % item 187
                        finalize(S8)
                    end
                ; true ->
                    % item 57
                    if LastModified > IfModifiedSince -> 
                        % item 371
                        % Precondition Failed
                        error(412, S3)
                    ; true ->
                        % item 284
                        {Expires, S4} = call(expires, S3),
                        S5 = set_etag(ETag, S4),
                        S6 = set_expires(Expires, S5),
                        % item 304
                        IfNoneMatch = 
                            elli_request:get_header(<<"If-None-Match">>, Req),
                        % item 36
                        if IfNoneMatch =:= undefined -> 
                            % item 39
                            if IfNoneMatch =:= <<"*">> -> 
                                % item 44
                                % Not Modified
                                error(304, S6)
                            ; true ->
                                % item 298
                                ETagMatches = 
                                    match_etag(ETag, IfMatchHeader),
                                % item 45
                                if ETagMatches -> 
                                    % item 44
                                    % Not Modified
                                    error(304, S6)
                                ; true ->
                                    % item 46
                                    S7 = set_last_modified(LastModified, S6),
                                    S8 = S7, 
                                    
                                    % call(provide_content, S7),
                                    
                                    io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                                    % item 187
                                    finalize(S8)
                                end
                            end
                        ; true ->
                            % item 46
                            S7 = set_last_modified(LastModified, S6),
                            S8 = S7, 
                            
                            % call(provide_content, S7),
                            
                            io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                            % item 187
                            finalize(S8)
                        end
                    end
                end
            end
        ; true ->
            % item 26
            if IfMatchHeader =:= <<"*">> -> 
                % item 290
                {LastModified, S3} = call(last_modified, S2),
                % item 302
                if LastModified =:= undefined -> 
                    % item 284
                    {Expires, S4} = call(expires, S3),
                    S5 = set_etag(ETag, S4),
                    S6 = set_expires(Expires, S5),
                    % item 304
                    IfNoneMatch = 
                        elli_request:get_header(<<"If-None-Match">>, Req),
                    % item 36
                    if IfNoneMatch =:= undefined -> 
                        % item 39
                        if IfNoneMatch =:= <<"*">> -> 
                            % item 44
                            % Not Modified
                            error(304, S6)
                        ; true ->
                            % item 298
                            ETagMatches = 
                                match_etag(ETag, IfMatchHeader),
                            % item 45
                            if ETagMatches -> 
                                % item 44
                                % Not Modified
                                error(304, S6)
                            ; true ->
                                % item 46
                                S7 = set_last_modified(LastModified, S6),
                                S8 = S7, 
                                
                                % call(provide_content, S7),
                                
                                io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                                % item 187
                                finalize(S8)
                            end
                        end
                    ; true ->
                        % item 46
                        S7 = set_last_modified(LastModified, S6),
                        S8 = S7, 
                        
                        % call(provide_content, S7),
                        
                        io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                        % item 187
                        finalize(S8)
                    end
                ; true ->
                    % item 289
                    IfModifiedSince =
                        elli_request:get_header(<<"If-Modified-Since">>, Req),
                    % item 33
                    if IfModifiedSince =:= undefined -> 
                        % item 284
                        {Expires, S4} = call(expires, S3),
                        S5 = set_etag(ETag, S4),
                        S6 = set_expires(Expires, S5),
                        % item 304
                        IfNoneMatch = 
                            elli_request:get_header(<<"If-None-Match">>, Req),
                        % item 36
                        if IfNoneMatch =:= undefined -> 
                            % item 39
                            if IfNoneMatch =:= <<"*">> -> 
                                % item 44
                                % Not Modified
                                error(304, S6)
                            ; true ->
                                % item 298
                                ETagMatches = 
                                    match_etag(ETag, IfMatchHeader),
                                % item 45
                                if ETagMatches -> 
                                    % item 44
                                    % Not Modified
                                    error(304, S6)
                                ; true ->
                                    % item 46
                                    S7 = set_last_modified(LastModified, S6),
                                    S8 = S7, 
                                    
                                    % call(provide_content, S7),
                                    
                                    io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                                    % item 187
                                    finalize(S8)
                                end
                            end
                        ; true ->
                            % item 46
                            S7 = set_last_modified(LastModified, S6),
                            S8 = S7, 
                            
                            % call(provide_content, S7),
                            
                            io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                            % item 187
                            finalize(S8)
                        end
                    ; true ->
                        % item 57
                        if LastModified > IfModifiedSince -> 
                            % item 371
                            % Precondition Failed
                            error(412, S3)
                        ; true ->
                            % item 284
                            {Expires, S4} = call(expires, S3),
                            S5 = set_etag(ETag, S4),
                            S6 = set_expires(Expires, S5),
                            % item 304
                            IfNoneMatch = 
                                elli_request:get_header(<<"If-None-Match">>, Req),
                            % item 36
                            if IfNoneMatch =:= undefined -> 
                                % item 39
                                if IfNoneMatch =:= <<"*">> -> 
                                    % item 44
                                    % Not Modified
                                    error(304, S6)
                                ; true ->
                                    % item 298
                                    ETagMatches = 
                                        match_etag(ETag, IfMatchHeader),
                                    % item 45
                                    if ETagMatches -> 
                                        % item 44
                                        % Not Modified
                                        error(304, S6)
                                    ; true ->
                                        % item 46
                                        S7 = set_last_modified(LastModified, S6),
                                        S8 = S7, 
                                        
                                        % call(provide_content, S7),
                                        
                                        io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                                        % item 187
                                        finalize(S8)
                                    end
                                end
                            ; true ->
                                % item 46
                                S7 = set_last_modified(LastModified, S6),
                                S8 = S7, 
                                
                                % call(provide_content, S7),
                                
                                io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                                % item 187
                                finalize(S8)
                            end
                        end
                    end
                end
            ; true ->
                % item 291
                ETagMatches = 
                    match_etag(ETag, IfMatchHeader),
                % item 29
                if ETagMatches -> 
                    % item 290
                    {LastModified, S3} = call(last_modified, S2),
                    % item 302
                    if LastModified =:= undefined -> 
                        % item 284
                        {Expires, S4} = call(expires, S3),
                        S5 = set_etag(ETag, S4),
                        S6 = set_expires(Expires, S5),
                        % item 304
                        IfNoneMatch = 
                            elli_request:get_header(<<"If-None-Match">>, Req),
                        % item 36
                        if IfNoneMatch =:= undefined -> 
                            % item 39
                            if IfNoneMatch =:= <<"*">> -> 
                                % item 44
                                % Not Modified
                                error(304, S6)
                            ; true ->
                                % item 298
                                ETagMatches = 
                                    match_etag(ETag, IfMatchHeader),
                                % item 45
                                if ETagMatches -> 
                                    % item 44
                                    % Not Modified
                                    error(304, S6)
                                ; true ->
                                    % item 46
                                    S7 = set_last_modified(LastModified, S6),
                                    S8 = S7, 
                                    
                                    % call(provide_content, S7),
                                    
                                    io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                                    % item 187
                                    finalize(S8)
                                end
                            end
                        ; true ->
                            % item 46
                            S7 = set_last_modified(LastModified, S6),
                            S8 = S7, 
                            
                            % call(provide_content, S7),
                            
                            io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                            % item 187
                            finalize(S8)
                        end
                    ; true ->
                        % item 289
                        IfModifiedSince =
                            elli_request:get_header(<<"If-Modified-Since">>, Req),
                        % item 33
                        if IfModifiedSince =:= undefined -> 
                            % item 284
                            {Expires, S4} = call(expires, S3),
                            S5 = set_etag(ETag, S4),
                            S6 = set_expires(Expires, S5),
                            % item 304
                            IfNoneMatch = 
                                elli_request:get_header(<<"If-None-Match">>, Req),
                            % item 36
                            if IfNoneMatch =:= undefined -> 
                                % item 39
                                if IfNoneMatch =:= <<"*">> -> 
                                    % item 44
                                    % Not Modified
                                    error(304, S6)
                                ; true ->
                                    % item 298
                                    ETagMatches = 
                                        match_etag(ETag, IfMatchHeader),
                                    % item 45
                                    if ETagMatches -> 
                                        % item 44
                                        % Not Modified
                                        error(304, S6)
                                    ; true ->
                                        % item 46
                                        S7 = set_last_modified(LastModified, S6),
                                        S8 = S7, 
                                        
                                        % call(provide_content, S7),
                                        
                                        io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                                        % item 187
                                        finalize(S8)
                                    end
                                end
                            ; true ->
                                % item 46
                                S7 = set_last_modified(LastModified, S6),
                                S8 = S7, 
                                
                                % call(provide_content, S7),
                                
                                io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                                % item 187
                                finalize(S8)
                            end
                        ; true ->
                            % item 57
                            if LastModified > IfModifiedSince -> 
                                % item 371
                                % Precondition Failed
                                error(412, S3)
                            ; true ->
                                % item 284
                                {Expires, S4} = call(expires, S3),
                                S5 = set_etag(ETag, S4),
                                S6 = set_expires(Expires, S5),
                                % item 304
                                IfNoneMatch = 
                                    elli_request:get_header(<<"If-None-Match">>, Req),
                                % item 36
                                if IfNoneMatch =:= undefined -> 
                                    % item 39
                                    if IfNoneMatch =:= <<"*">> -> 
                                        % item 44
                                        % Not Modified
                                        error(304, S6)
                                    ; true ->
                                        % item 298
                                        ETagMatches = 
                                            match_etag(ETag, IfMatchHeader),
                                        % item 45
                                        if ETagMatches -> 
                                            % item 44
                                            % Not Modified
                                            error(304, S6)
                                        ; true ->
                                            % item 46
                                            S7 = set_last_modified(LastModified, S6),
                                            S8 = S7, 
                                            
                                            % call(provide_content, S7),
                                            
                                            io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                                            % item 187
                                            finalize(S8)
                                        end
                                    end
                                ; true ->
                                    % item 46
                                    S7 = set_last_modified(LastModified, S6),
                                    S8 = S7, 
                                    
                                    % call(provide_content, S7),
                                    
                                    io:fwrite(standard_error, "State: ~p~n", [exchange(S8)]),
                                    % item 187
                                    finalize(S8)
                                end
                            end
                        end
                    end
                ; true ->
                    % item 32
                    % Precondition Failed
                    error(412, S2)
                end
            end
        end
    ; true ->
        % item 286
        {PreviouslyExisted, S2} =
            call(previously_existed, S1),
        % item 9
        if PreviouslyExisted -> 
            % item 287
            {MovedPermanently, S3} = 
                call(moved_permanently, S2),
            % item 58
            if MovedPermanently -> 
                % item 61
                % Moved Permanently
                error(301, S3)
            ; true ->
                % item 288
                {MovedTemporarily, S4} =
                    call(moved_temporarily, S3),
                % item 62
                if MovedTemporarily -> 
                    % item 65
                    % Moved Temporarily
                    error(307, S4)
                ; true ->
                    % item 66
                    % Gone
                    error(410, S4)
                end
            end
        ; true ->
            % item 12
            % Not Found
            error(404, S2)
        end
    end
.

handle_request(State) ->
    % item 270
    {Pong, S1} = call(ping, State),
    % item 217
    if Pong =:= pong -> 
        % item 271
        {ServiceAvailable, S2} = call(service_available, S1),
        % item 220
        if ServiceAvailable -> 
            % item 274
            {KnownMethods, S3} = call(known_methods, S2),
            Method = elli_request:method(request(S3)),
            IsKnownMethod = lists:member(Method, KnownMethods),
            % item 223
            if IsKnownMethod -> 
                % item 275
                {UriTooLong, S4} = call(uri_too_long, S3),
                % item 227
                if UriTooLong -> 
                    % item 230
                    % Request-URI Too Long
                    respond(414, S4)
                ; true ->
                    % item 276
                    {AllowedMethods, S5} = call(allowed_methods, S4),
                    IsAllowedMethod = lists:member(Method, AllowedMethods),
                    % item 231
                    if IsAllowedMethod -> 
                        % item 277
                        {MalformedRequest, S6} = call(malformed_request, S5),
                        % item 278
                        if MalformedRequest -> 
                            % item 280
                            % Bad Request
                            respond(400, S6)
                        ; true ->
                            % item 281
                            {IsAuthorized, S7} = call(is_authorized, S6),
                            % item 240
                            if IsAuthorized =:= true -> 
                                % item 283
                                {Forbidden, S8} = call(forbidden, S7),
                                % item 243
                                if Forbidden -> 
                                    % item 246
                                    % Forbidden
                                    respond(403, S7)
                                ; true ->
                                    % item 2530001
                                    if Method =:= 'GET' orelse 'HEAD' -> 
                                        % item 264
                                        get_flow(S8)
                                    ; true ->
                                        % item 2530002
                                        if Method =:= 'POST' -> 
                                            % item 265
                                            post_flow(S8)
                                        ; true ->
                                            % item 2530003
                                            if Method =:= 'PUT' -> 
                                                % item 266
                                                put_flow(S8)
                                            ; true ->
                                                % item 2530004
                                                if Method =:= 'DELETE' -> 
                                                    % item 267
                                                    delete_flow(S8)
                                                ; true ->
                                                    % item 2530005
                                                    if Method =:= 'OPTIONS' -> 
                                                        []
                                                    ; true ->
                                                        % item 2530006
                                                        throw("Unexpected switch value")
                                                    end,
                                                    % item 268
                                                    options_flow(S8)
                                                end
                                            end
                                        end
                                    end
                                end
                            ; true ->
                                % item 247
                                %% TODO,
                                % item 282
                                %% {error, Reason} ->
                                %%    error_response(Reason, Rs1, Rd1);
                                %% {halt, Code}  ->
                                %%    respond(Code, Rs1, Rd1);
                                %% AuthHead ->
                                %%    RdAuth = emr:set_resp_header(<<"WWW-Authenticate">>, AuthHead, Rd1),
                                respond(401, S7)
                            end
                        end
                    ; true ->
                        % item 250
                        SAllow = set_resp_header(
                            <<"Allow">>, AllowedMethods, S5),
                        
                        % Method Not Allowed
                        respond(405, SAllow)
                    end
                end
            ; true ->
                % item 226
                % Not Implemented
                respond(501, S3)
            end
        ; true ->
            % item 219
            % Service Unavailable
            respond(503, S2)
        end
    ; true ->
        % item 273
        % Service Unavailable
        respond(503, S1)
    end
.

has_resp_body(State) ->
    % item 345
    emx:has_resp_body(exchange(State))
.

options_flow(State) ->
    % item 387
    State
.

post_flow(State) ->
    % item 294
    Req = request(State),
    % item 389
    {ValidContentHeaders, S1} = 
        call(valid_content_headers, State),
    % item 392
    if ValidContentHeaders -> 
        % item 390
        {KnownContentType, S2} =
            call(known_content_type, S1),
        % item 394
        if KnownContentType -> 
            % item 391
            {ValidEntityLength, S3} =
                call(valid_entity_length, S2),
            % item 396
            if ValidEntityLength -> 
                % item 388
                {ResourceExists, S4} = 
                    call(resource_exists, S3),
                % item 72
                if ResourceExists -> 
                    % item 306
                    {LastModified, S5} = call(last_modified, S4),
                    % item 307
                    if LastModified =:= undefined -> 
                        % item 295
                        IfModifiedSince =
                            elli_request:get_header(<<"If-Modified-Since">>, Req),
                        % item 75
                        if IfModifiedSince =:= undefined -> 
                            % item 312
                            {ContentTypesAccepted, S6} = 
                                call(content_types_accepted, S5),
                            % item 81
                            if ContentTypesAccepted =:= [] -> 
                                % item 112
                                % Unsupported MediaType
                                respond(415, S6)
                            ; true ->
                                % item 315
                                {ProcessResult, S7} = call(process_post, S6),
                                % item 325
                                if ProcessResult =:= true -> 
                                    % item 324
                                    S8 = encode_body_if_set(S7),
                                    % item 179
                                    finalize(S8)
                                ; true ->
                                    % item 323
                                    {redirect, Url} = ProcessResult,
                                    S8 = set_header_if_not_set(<<"Location">>, Url, S7),
                                    % item 100
                                    % See Other
                                    respond(303, S8)
                                end
                            end
                        ; true ->
                            % item 181
                            if LastModified > IfModifiedSince -> 
                                % item 312
                                {ContentTypesAccepted, S6} = 
                                    call(content_types_accepted, S5),
                                % item 81
                                if ContentTypesAccepted =:= [] -> 
                                    % item 112
                                    % Unsupported MediaType
                                    respond(415, S6)
                                ; true ->
                                    % item 315
                                    {ProcessResult, S7} = call(process_post, S6),
                                    % item 325
                                    if ProcessResult =:= true -> 
                                        % item 324
                                        S8 = encode_body_if_set(S7),
                                        % item 179
                                        finalize(S8)
                                    ; true ->
                                        % item 323
                                        {redirect, Url} = ProcessResult,
                                        S8 = set_header_if_not_set(<<"Location">>, Url, S7),
                                        % item 100
                                        % See Other
                                        respond(303, S8)
                                    end
                                end
                            ; true ->
                                % item 184
                                % generate_etag/2,
                                % item 185
                                % expires/2,
                                % item 186
                                % Not Modified
                                respond(304, S5)
                            end
                        end
                    ; true ->
                        % item 312
                        {ContentTypesAccepted, S6} = 
                            call(content_types_accepted, S5),
                        % item 81
                        if ContentTypesAccepted =:= [] -> 
                            % item 112
                            % Unsupported MediaType
                            respond(415, S6)
                        ; true ->
                            % item 315
                            {ProcessResult, S7} = call(process_post, S6),
                            % item 325
                            if ProcessResult =:= true -> 
                                % item 324
                                S8 = encode_body_if_set(S7),
                                % item 179
                                finalize(S8)
                            ; true ->
                                % item 323
                                {redirect, Url} = ProcessResult,
                                S8 = set_header_if_not_set(<<"Location">>, Url, S7),
                                % item 100
                                % See Other
                                respond(303, S8)
                            end
                        end
                    end
                ; true ->
                    % item 309
                    {PreviouslyExisted, S5} =
                        call(previously_existed, S4),
                    % item 104
                    if PreviouslyExisted -> 
                        % item 310
                        {MovedPermanently, S6} = 
                            call(moved_permanently, S5),
                        % item 113
                        if MovedPermanently -> 
                            % item 120
                            % Moved Permanently
                            respond(301, S6)
                        ; true ->
                            % item 311
                            {MovedTemporarily, S7} = 
                                call(moved_temporarily, S6),
                            % item 121
                            if MovedTemporarily -> 
                                % item 124
                                % Moved Temporarily
                                respond(410, S7)
                            ; true ->
                                % item 125
                                % Gone
                                respond(410, S7)
                            end
                        end
                    ; true ->
                        % item 313
                        {AllowMissingPost, S6} = 
                            call(allow_missing_post, S5),
                        % item 117
                        if AllowMissingPost -> 
                            % item 337
                            {ContentTypesAccepted, S7} = 
                                call(content_types_accepted, S6),
                            % item 126
                            if ContentTypesAccepted =:= [] -> 
                                % item 339
                                {_ProcessResult, S8} = call(process_post, S7),
                                % item 314
                                Location = 
                                    get_resp_header(<<"Location">>, S8),
                                % item 134
                                if Location =/= undefined -> 
                                    % item 137
                                    % Created
                                    respond(201, S8)
                                ; true ->
                                    % item 180
                                    finalize(S8)
                                end
                            ; true ->
                                % item 338
                                % Unsupported MediaType
                                respond(415, S7)
                            end
                        ; true ->
                            % item 116
                            % Not Found
                            respond(404, S6)
                        end
                    end
                end
            ; true ->
                % item 398
                % Request Entity Too Large
                respond(413, S3)
            end
        ; true ->
            % item 399
            % Unsupported Media Type
            respond(415, S2)
        end
    ; true ->
        % item 400
        % Not Implemented
        respond(501, S1)
    end
.

put_flow(State) ->
    % item 386
    State
.

request(State) ->
    % item 384
    Exchange = State#machine_flow_state.exchange,
    Exchange#machine_exchange.req
.

respond(Code, State) ->
    % item 385
    {Code, State}
.

%%
%% Helpers
%%

set_etag(_Tag, State) ->
    State.

set_expires(_Expires, State) ->
    State.

set_last_modified(_LastModified, State) ->
    State.

set_resp_header(_Header, _Value, State) ->
    State.

get_resp_header(_Header, State) ->
    {undefined, State}.

match_etag(_Tag, _TagList) ->
    false.

encode_body_if_set(State) ->
    State.

set_header_if_not_set(_Header, _Value, State) ->
    State.
